language: c

git:
  depth: 1
  quiet: false
  submodules: true

jobs:
  include:
  - name: "Linux: Clang 9"
    os: linux
    dist: bionic
    compiler: clang
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
        packages: [clang-9, libstdc++-9-dev, ninja-build, libglew-dev,
                    libsndio-dev, libflac-dev, libspeex-dev, libopus-dev,
                    libogg-dev, libvorbis-dev, libasound2-dev, libvorbis-dev,
                    libxinerama-dev, libxcursor-dev, libxi-dev, libxrandr-dev, cppcheck]
    env:
      - CC=clang-9 CXX=clang++-9

  - name: "Windows: Visual Studio 2017"
    os: windows
    env:
      - MSBUILD_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin"


before_install: 
    - chmod +x ./.travis/install-cmake.sh ./.travis/build.sh
    - ./.travis/install-cmake.sh
script: 
    - ./.travis/build.sh
    - cppcheck src/ --enable=warning,style,performance,portability --inconclusive --error-exitcode=1
    - cppcheck lib/Physics/src --enable=warning,style,performance,portability --inconclusive --error-exitcode=1
    - build/BigBalls --test
    
after_success:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL
after_failure:
    - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL
